### ISSUE TITLE
'Creating Color Palette' doesn't work.

### ISSUE THREAD

**Issue by Real-Moomin** [eddiesigner/sketch-dark-mode#13]
Hello, I'm Theo. I'm using 'Sketch Dark Mode' Plugin in the newest version(Sketch 69).

In this version, 'Creating Color Palette' doesn't work anymore though I assigned unique names to every single color.
I guess it happens after Sketch started offering new Symbol(Component) UI.

![image](https://user-images.githubusercontent.com/26920609/96393966-ba00a500-11fb-11eb-9f7a-84b92fab2cbb.png)

![image](https://user-images.githubusercontent.com/26920609/96393980-c1c04980-11fb-11eb-8489-2152a61917fb.png)

![image](https://user-images.githubusercontent.com/26920609/96393989-c71d9400-11fb-11eb-883b-200af27aad7b.png)

Please check out screenshots. I tried to test with new Sketch file.
Thanks.

**Comment by eddiesigner** [comment]
Hi, thanks for the feedback!

From the docs:

> Sketch 69 introduces a new Color Variables feature.
Color Variables replace the previously existing colors object in Document with a new one: swatches. It is an array of Color Variables, internally referred to as Swatches, which you can modify directly.

Apparently in the last version they replaced the colors object that this plugin uses. I will work on a new version that supports the recent changes in their API 👍

**Comment by 940822tw** [comment]
@eddiesigner Sounds great.
I hope that everyone can use this plugin again as soon as possible ! 👍
Have a nice day!

**Comment by 940822tw** [comment]
And I wonder when will you distribute a hot-fix(or a new version) for plugin. Being currently working on Dark Mode Project on our product, our team is waiting for issue fixed.

Thanks, again I really appreciate.

**Comment by eddiesigner** [comment]
I'm not sure, I hope I can release a new version next week or so.

**Comment by 940822tw** [comment]
Got it ! Thank you, and have a nice day ! 😁

**Comment by eddiesigner** [comment]
[Version 2.5.0](https://github.com/eddiesigner/sketch-dark-mode/releases/tag/v2.5.0) suports Color Vriables 😃 

More details here: https://github.com/eddiesigner/sketch-dark-mode/wiki/How-to-use-Sketch-Dark-Mode

**Comment by Real-Moomin** [comment]
@eddiesigner , Thank you so much! 😊
