### ISSUE TITLE
Issue on "Color Library" using Color Variable

### ISSUE THREAD

**Issue by Real-Moomin** [eddiesigner/sketch-dark-mode#15]
Hello, It's Theo.

Thanks for last update. Now we adopt Dark Mode Plugin very smoothly.
I and Our team become a heavy users :)

But I have same problem when I try to change colors in "library file".
Although I assigned unique name to colors in library file, the plugin show dialog following

![image](https://user-images.githubusercontent.com/26920609/97953165-04c91200-1de3-11eb-826d-1d5fb5b5d7f1.png)

I think you missed it when you fix in the latest update. (If I'm wrong, please tell me how to solve it 😓)
Would you please handle it?

Thanks for everything.

**Comment by eddiesigner** [comment]
Hi,

Thanks for the heads up! I already fixed the issue of not loading color variables in some cases, specially with libraries, please try again with the latest version of the plugin (2.6.0).

**Comment by Real-Moomin** [comment]
Thank you so much :) I'll check them out !
