### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by PeakXing** [eddiesigner/sketch-dark-mode#18]
Hello, I am glad to have this plug-in, but there are many colors in our specification that have transparency. I searched the Internet and did not find a corresponding plug-in that supports transparency.
May I ask why the color cannot support transparency?

**Comment by eddiesigner** [comment]
Hi, this is because Sketch saves colors as hex values, although I just found that it seems possible to keep the opacity value as part of the hex value. I will give it a try as soon as I can and hope I can release a new version with transparency support in the following weeks.

**Comment by eddiesigner** [comment]
I just released [version 3.1.0 ](https://github.com/eddiesigner/sketch-dark-mode/releases/tag/v3.1.0) which supports transparency.

Cheers ✌️
