### ISSUE TITLE
What about transparency?

### ISSUE THREAD

**Issue by kckfm** [eddiesigner/sketch-dark-mode#22]
I have some colors that use transparency.
The index in the red box means % of transparency. In the image below the colors looks the same.
![image](https://user-images.githubusercontent.com/1556338/104558350-5693e100-564b-11eb-889c-d2559dd61b1f.png)

Do you handle transparent colors?

Thanks!
SK

**Comment by eddiesigner** [comment]
I just released [version 3.1.0](https://github.com/eddiesigner/sketch-dark-mode/releases/tag/v3.1.0) which supports transparency ✌️
