### ISSUE TITLE
Gradient support 🙏

### ISSUE THREAD

**Issue by sarahlafeuil** [eddiesigner/sketch-dark-mode#7]
Hi
Thank you for this pluggin, it saves me a lot of headaches actually :)

Could you consider adding gradient support?
I have a massive mobile app project, using lots of gradients. It has several skins on light theme and I have to replicate them on dark theme).

Thank you so much !!!

Sarah

**Comment by eddiesigner** [comment]
Hey, thanks for using it!

After checking the Sketch documentation I found a possible way to implement this but currently I'm quite busy with other stuff, as soon as I have some spare time I will try to implement it.

**Comment by eddiesigner** [comment]
From version [2.4.0](https://github.com/eddiesigner/sketch-dark-mode/releases/tag/v2.4.0) gradients are now supported, please take a look first to [the notes](https://github.com/eddiesigner/sketch-dark-mode/wiki/How-to-use-Sketch-Dark-Mode#work-with-gradients) about gradients.
