### ISSUE TITLE
Please Add support for Exporting Assets

### ISSUE THREAD

**Issue by yixe** [eddiesigner/sketch-dark-mode#9]
Coming from receptiryaki plugin (https://github.com/receptiryaki/darkside), I love everything about this plugin but wish it had the ability to export Color assets to XCode. This has the potential to be my all around dark/light mode tool 🖤

**Comment by eddiesigner** [comment]
I'm afraid that's a feature I don't plan to implement, plus there are other plugins out there that perform that specific task very well 🙂
